### ISSUE TITLE
installation script error 

### ISSUE THREAD

**Issue by nsk** [abstractfoundry/lumicube#19]
Installing the Abstract Foundry Daemon...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Traceback (most recent call last):
  File "/dev/fd/63", line 204, in <module>
  File "/dev/fd/63", line 85, in install_daemon
  File "/dev/fd/63", line 21, in run
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'curl -fL https://www.abstractfoundry.com/lumicube/download/Daemon-1.8-x64.AppImage > /home/pi/AbstractFoundry/Daemon/Software/Daemon-1.8-x64.AppImage' returned non-zero exit status 22.

**Comment by Ckopulos1** [comment]
I also experienced this issue.  Does anyone have a solution?

**Comment by robcz** [comment]
It's because platform_variant() in install.py is returning x64 due to what it's getting back from platform.machine().  I just forced it to return 'arm' and it built the correct URL to the Daemon AppImage file and it made it past that error to properly install.

**Comment by Gokux** [comment]
If you have the problem after an OS update, you can also simply add "arm_64bit=0" in the "/boot/config.txt" file and reboot.

**Comment by jclauzel** [comment]
I had no time before but yesterday I started building and completed my Lumicube fully working.
I realized it gave some people some headache as I did run into many issues and managed to fix them so, please find below how I did that, hope this helps. The root cause of these issues are multiple ascending software compatibility breaking issues but the below should at least provide some solution for folks that are trying to make a clean installation today.

Use RASPI OS 32 LEGACY image.
sudo apt-get update && sudo apt-get upgrade -y && sudo apt install pulseaudio pulseaudio-utils python3-psutil
sudo apt autoremove
python3 <(curl -fL https://www.abstractfoundry.com/lumicube/download/install.py)
At this point it fails downloading the x64 app package as it needs the ARM version!
Download a copy of the lumicube-daemon
git clone https://github.com/abstractfoundry/lumicube-daemon
cd lumicube-daemon/
sudo nano install.py

Find the following platform_variant function in install.py: 
def platform_variant():
    return 'arm' if 'arm' in platform.machine() else 'x64'
and change it to just return arm as follows:
def platform_variant():
    return 'arm' 
Run install.py again to complete the install.
python3 install.py
Now the script should complete…
Set the service to start automatically:
sudo loginctl enable-linger
sudo reboot now
Check java deamon is running (wait a bit) it should fail after some time (a minute or two)…
systemctl --user status foundry-daemon.service

To fix this you need to do the following:
sudo nano /boot/config.txt
add at the top the following line:
arm_64bit=0
Save, exit 
sudo reboot now
I did try to add the following packages I am not sure it really helped but I did that so mentioning it:
sudo apt install pulseaudio-utils pulseaudio libalsaplayer-dev portaudio19-dev

Yeayy at this point you should now be able to connect to the web interface… however speaker is likely not working…. 
You should see when invoking the speaker an error similar to: “java.net.SocketException: Could not connect to /tmp/foundry_python_service.sock”
The root cause is that the software is made of two key parts, some Java code and some Python code.
The python code uses and references old versions of Flask and Werkzeug libraries. The web service that uses that then fails initializing and therefore the Java web interface can’t connect to it.
cd /tmp
ls
You should see both .sock descriptors:
foundry_daemon.sock
foundry_python_service.sock
If you don’t see foundry_python_service.sock that’s because the python web service failed initialize as mentioned above.
cd  ~/lumicube-daemon/src/main/resources/META-INF/resources/python/global_service
try to run:
python3 service.py
and it should fail with something like: “ImportError: cannot import name 'url_quote' from 'werkzeug.urls'”
in that situation I fixed this by forcing an upgrade of these libraries: 
pip install --upgrade Flask
pip install --upgrade  Werkzeug
try running again:
python3 service.py
At this point it should execute fine and not spew any error.
sudo reboot now
At this point I got everything running and working.

Overall, the critical steps here are:
1 – in /boot/config.txt
Add at the beginning : arm_64bit=0
sudo reboot now
This needs to be done in the very first setup stages (even before the: “sudo apt-get update && sudo apt-get upgrade -y && sudo apt install pulseaudio pulseaudio-utils python3-psutil”).
I think this should even fix the install.py issue failing to download the right appx package if not patch the install.py (by downloading a git clone of https://github.com/abstractfoundry/lumicube-daemon) by forcing it to return arm only as mentioned above. 
def platform_variant():
    return 'arm' 
I have seen on the discord that it looks like some forks of the intall.py script has been done with this but again this was not enough. This helps the install.py to complete with no errors but for things to fully work I had to set arm_64bit=0 had in /boot/config.txt for things to work for me or you end up with some java runtime errors later on regarding the VirtualMicrophone.
Exception in thread "main" java.lang.IllegalStateException: Error installing virtual microphone source.
	at com.abstractfoundry.daemon.audio.VirtualMicrophone.<init>(VirtualMicrophone.java:50)
	at com.abstractfoundry.daemon.Daemon.<init>(Daemon.java:69)
	at com.abstractfoundry.daemon.Daemon.main(Daemon.java:113)
This was fixed by setting /boot/config.txt  arm_64bit=0 and reboothing.

2 – Update the pythons Flask and Werkzeug libs as mentioned above once the web ui is working to get the speaker dependency libraries updated:
pip install --upgrade Flask
pip install --upgrade  Werkzeug
sudo reboot now

That’s all folks!

**Comment by ItsaBastI** [comment]
> That’s all folks!

I am so happy I've found your instructions. I bought a LumiCube through the campaign and two more when they announced the shutdown. It's only thanks to your explanation that I see a "Hello World" scrolling across my Cube at the moment. I've never been so happy seeing a "Hello World" :-D Thanks a lot!

**Comment by chrislibuilds** [comment]
I've managed to get this running on Debian 12 (64-bit). More information: [https://github.com/koromar/lumicube-daemon-2024](https://github.com/koromar/lumicube-daemon-2024)
